Repository Rose-Hacks/rosehack2024, pull requests merged in 2023-11, with the labels that each got.

#43 about section
  public/svg/about/borderbg.png
  public/svg/about/circle1.svg
  public/svg/about/circle2.svg
  public/svg/about/flow.svg
  src/components/static/about/About.jsx
  src/components/static/about/Circle.js
  tailwind.config.js
Labels: ready to review

#47 Add volunteer component
  src/components/static/prelive/getInvolved/Volunteer.jsx
Labels: landing, ready to review

#53 countdown responsiveness
  src/components/static/upcoming/Content.jsx
Labels: ready to review, responsive

#63 skinned error pages
  src/components/dynamic/Error.jsx
  src/components/static/prelive/Prelive.jsx
  src/data/Releases.js
Labels: prelive
