Repository Rose-Hacks/rosehack2024, pull requests merged in 2024-01, with the labels that each got.

#125 Fuyuki/FooterAdjustment
  src/components/static/live/Footer.jsx
Labels: ready to review

#128 Update Judge
  public/judges/KaranBhogal.webp
  src/components/dynamic/Navigation.jsx
  src/components/static/live/board/Boards.jsx
  src/components/static/live/judges/Judges.jsx
  src/data/static/Judges.js
Labels: landing, portal

#141 created tracks component
  src/components/static/live/tracks/Tracks.jsx
  src/data/static/Tracks.js
Labels: ready to review

#142 committee reorder, judge update, sponsor remove
  public/judges/WestinMontano.webp
  src/components/static/live/Sponsors.jsx
  src/data/static/Committees.js
  src/data/static/Judges.js
  src/data/static/Sponsors.js
Labels: live

#150 tracks ui fix
  src/components/static/live/tracks/Tracks.jsx
Labels: ready to review

#156 Update Tracks
  src/data/static/FAQ.js
Labels: ready to review

#157 Add New Judges
  public/judges/Qian.webp
  public/judges/Steve.webp
  src/data/static/Judges.js
Labels: ready to review
